import QueryWrapper from './util/QueryWrapper'
import 'monday-ui-react-core/dist/main.css'
import './styles/style.scss'
import SurfaceControlNav from './components/SurfaceControlNav'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <QueryWrapper>
          <main className='layout'>
            <SurfaceControlNav />
            {children}
          </main>
        </QueryWrapper>
      </body>
    </html>
  )
}
