
import QueryWrapper from './util/QueryWrapper'
import 'monday-ui-react-core/dist/main.css'
import './styles/style.scss'
import SurfaceControlNav from './components/SurfaceControlNav'
// import {ReactQueryDevtools} from '@tanstack/react-query-devtools'
export const metadata = {
  title: 'lundi.com',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
      </head>
      <body>
        <QueryWrapper>
          {/* <ReactQueryDevtools /> */}
          <main className='layout'>
            <SurfaceControlNav />
            {children}
          </main>
        </QueryWrapper>
      </body>
    </html>
  )
}
